# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppleWeather' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppleWeather
pod 'lottie-ios'
pod 'Moya', '~> 14.0'
end
